### ISSUE TITLE
Access Violation error

### ISSUE THREAD

**Issue by PeterBBCUser** [geraldholdsworth/DiscImageManager#26] opened 2023-03-03 11:50 UTC
When trying to defrag a large ADFS (scsi0.dat) hard drive image I have, I get the access Violation error (on windows).
![DiscManager Access violation](https://user-images.githubusercontent.com/33581895/222712833-66b4f9cf-af33-496a-b022-5f7bdbc646e6.jpg)

**Comment by geraldholdsworth** [comment] 2023-03-03 12:02
This appears to happen when there are a large number of files. Happens on macOS too.

**Comment by geraldholdsworth** [comment] 2023-03-03 12:48
Looks like it is timing out when deleting files. This is on a New Map ADFS image. Not sure why it is taking a long time to delete files

**Comment by geraldholdsworth** [comment] 2023-03-03 13:57
So, this was not caused by a timeout but by trying to access more elements in an array than exist. However, this bug has shown a few other bugs and issues - not least the time taken to delete files (which I've found the reason for), but also that when deleting archives, it deletes everything inside first instead of just the archive itself.

**Comment by geraldholdsworth** [comment] 2023-03-06 18:32
This will be fixed in the next release, which I'll put out over the next couple of days. This particular issue has thrown up, so far, three bugs and one issue which would be a direct cause of this specific issue.

**Comment by geraldholdsworth** [comment] 2023-03-10 08:22
I have made available 1.45.1 which addresses the issues raised by this issue, and a few more.

**Comment by PeterBBCUser** [comment] 2023-03-10 19:16
Thank you and yes I can confirm that it work fine with this new version.

**Closed** 2023-03-10 19:16 UTC
